import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import Navbar from "@/components/shared/navbar/Navbar";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Footer from "@/components/shared/Footer";

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <ThemeProvider attribute="class">
        <body className={kanit.className}>
          <main className="w-full h-dvh overflow-hidden antialiased flex flex-col justify-between">
            <Navbar />
            {children}
            <Footer />
          </main>
          <Toaster />
        </body>
      </ThemeProvider>
    </html>
  );
}
